# Generated by Django 3.1.1 on 2020-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='game',
            field=models.ManyToManyField(to='authapp.Game'),
        ),
    ]
