# Generated by Django 3.1.1 on 2020-10-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20201003_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
