# Generated by Django 3.1.1 on 2020-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20201003_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
