# Generated by Django 3.1.1 on 2020-10-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20201003_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='game',
            new_name='games',
        ),
    ]
